import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import Header from "@/components/ui/layout/header";
import { siteConfig } from "@/config/siteConfig";
import { layoutConfig } from "@/config/layoutConfig";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth/auth";
import AppLoader from "@/hoc/app-loader";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/ui/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SessionProvider session={session}>
            <AppLoader>
              <div className="flex min-h-screen flex-col justify-between">
                <div className="flex flex-col">
                  <Header />
                  <main
                    className={`flex flex-col  mx-auto px-[24px] justify-start items-center`}
                  >
                    {children}
                  </main>
                </div>
                <footer
                  className={`w-full flex items-center justify-center py-3 text-gray-500 `}
                  style={{ height: layoutConfig.footerHeight }}
                >
                  <Footer />
                </footer>
              </div>
            </AppLoader>
          </SessionProvider>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
//https://image.tmdb.org/t/p/w500/d8duYyyC9J5T825Hg7grmaabfxQ.jpg
